# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
#
#Loom
#
loom_version=1.10-SNAPSHOT
#Modrinth
modrinth_versions=["1.21.6"]
#CurseForge
curseforge_id=601579
#Dependencies
required_dependencies=["fabric-api"]
optional_dependencies=["wthit", "emi", "modmenu"]
#`release`, `beta` or `alpha`
release_channel=alpha
#
# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.7
loader_version=0.16.14
fabric_version=0.128.1+1.21.7
#
# Mod Properties
#
mod_version=21.7.1
maven_group=de.ambertation
archives_base_name=wunderreich
#
# Dependencies
#
#rei_version=16.0.744
wthit_version=16.0.0
#emi_version=1.1.8+1.21
modmenu_version=15.0.0-beta.1
wunderlib_version=21.7.0