# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
#
#Loom
#
loom_version=1.15.5
#Modrinth
modrinth_versions=["26.1", "26.1.1", "26.1.2"]
#CurseForge
curseforge_id=601579
#Dependencies
required_dependencies=["fabric-api"]
optional_dependencies=["wthit", "emi", "modmenu"]
#`release`, `beta` or `alpha`
release_channel=alpha
#
# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=26.1.2
loader_version=0.19.3
fabric_version=0.155.2+26.1.2
#
# Mod Properties
#
mod_version=26.0.0
maven_group=de.ambertation
archives_base_name=wunderreich
#
# Dependencies
#
rei_version=26.1.819
wthit_version=19.0.1
#emi_version=1.1.8+1.21
modmenu_version=18.0.0
wunderlib_version=26.0.0