pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

apply from: "common-settings.gradle"

// #### Custom Settings ####

// Change the next line to disable local lib loading, even if the sibling folder exists
def allowLocalLibUse = true

// #### Logic ####
includeLocalLib('wunderlib', '../WunderLib', './wunderlib-composit.gradle', allowLocalLibUse)
